variables:
  IMAGE_NAME: dtoguzova/anno-items-api
  IMAGE_TAG: "1.1.0"


stages:
  - test
  - build


run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make && apt-get install -y git
  script:
    - make test


build_image:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - Dockerfile
  stage: build
  image: docker:23.0.1
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    API_PORT: "$API_PORT"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
